// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6651.DraftGoldieproject;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainRight1;
    public static SpeedController drivetrainLeft1;
    public static SpeedController drivetrainLeft2;
    public static SpeedController drivetrainRight2;
    public static RobotDrive drivetrainRobotDrive;
    public static SpeedController ballIntakeballIntake;
    public static SpeedController ballOutputballOutput;
    public static SpeedController ropeClimberropeClimber;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainRight1 = new Spark(2);
        LiveWindow.addActuator("Drive train", "Right 1", (Spark) drivetrainRight1);
        
        drivetrainLeft1 = new Spark(0);
        LiveWindow.addActuator("Drive train", "Left 1", (Spark) drivetrainLeft1);
        
        drivetrainLeft2 = new Spark(1);
        LiveWindow.addActuator("Drive train", "Left 2", (Spark) drivetrainLeft2);
        
        drivetrainRight2 = new Spark(3);
        LiveWindow.addActuator("Drive train", "Right 2", (Spark) drivetrainRight2);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainLeft1, drivetrainLeft2,
              drivetrainRight1, drivetrainRight2);
        
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.4);
        drivetrainRobotDrive.setMaxOutput(0.75);

        ballIntakeballIntake = new Spark(4);
        LiveWindow.addActuator("Ball Intake", "ballIntake", (Spark) ballIntakeballIntake);
        
        ballOutputballOutput = new Spark(5);
        LiveWindow.addActuator("Ball Output", "ballOutput", (Spark) ballOutputballOutput);
        
        ropeClimberropeClimber = new Spark(6);
        LiveWindow.addActuator("Rope Climber", "ropeClimber", (Spark) ropeClimberropeClimber);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
