// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::drivetrainRight1;
std::shared_ptr<SpeedController> RobotMap::drivetrainLeft1;
std::shared_ptr<SpeedController> RobotMap::drivetrainLeft2;
std::shared_ptr<SpeedController> RobotMap::drivetrainRight2;
std::shared_ptr<RobotDrive> RobotMap::drivetrainRobotDrive;
std::shared_ptr<SpeedController> RobotMap::ballIntakeballIntake;
std::shared_ptr<SpeedController> RobotMap::ballOutputballOutput;
std::shared_ptr<SpeedController> RobotMap::ropeClimberropeClimber;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    drivetrainRight1.reset(new Spark(2));
    lw->AddActuator("Drive train", "Right 1", std::static_pointer_cast<Spark>(drivetrainRight1));
    
    drivetrainLeft1.reset(new Spark(0));
    lw->AddActuator("Drive train", "Left 1", std::static_pointer_cast<Spark>(drivetrainLeft1));
    
    drivetrainLeft2.reset(new Spark(1));
    lw->AddActuator("Drive train", "Left 2", std::static_pointer_cast<Spark>(drivetrainLeft2));
    
    drivetrainRight2.reset(new Spark(3));
    lw->AddActuator("Drive train", "Right 2", std::static_pointer_cast<Spark>(drivetrainRight2));
    
    drivetrainRobotDrive.reset(new RobotDrive(drivetrainLeft1, drivetrainLeft2,
              drivetrainRight1, drivetrainRight2));
    
    drivetrainRobotDrive->SetSafetyEnabled(true);
        drivetrainRobotDrive->SetExpiration(0.1);
        drivetrainRobotDrive->SetSensitivity(0.4);
        drivetrainRobotDrive->SetMaxOutput(0.75);

    ballIntakeballIntake.reset(new Spark(4));
    lw->AddActuator("Ball Intake", "ballIntake", std::static_pointer_cast<Spark>(ballIntakeballIntake));
    
    ballOutputballOutput.reset(new Spark(5));
    lw->AddActuator("Ball Output", "ballOutput", std::static_pointer_cast<Spark>(ballOutputballOutput));
    
    ropeClimberropeClimber.reset(new Spark(6));
    lw->AddActuator("Rope Climber", "ropeClimber", std::static_pointer_cast<Spark>(ropeClimberropeClimber));
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
